/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)


type AfEvent string

// List of AfEvent
const (
        AfEvent_ACCESS_TYPE_CHANGE AfEvent = "ACCESS_TYPE_CHANGE"
        AfEvent_ANI_REPORT AfEvent = "ANI_REPORT"
        AfEvent_APP_DETECTION AfEvent = "APP_DETECTION"
        AfEvent_CHARGING_CORRELATION AfEvent = "CHARGING_CORRELATION"
        AfEvent_EPS_FALLBACK AfEvent = "EPS_FALLBACK"
        AfEvent_EXTRA_UE_ADDR AfEvent = "EXTRA_UE_ADDR"
        AfEvent_FAILED_QOS_UPDATE AfEvent = "FAILED_QOS_UPDATE"
        AfEvent_FAILED_RESOURCES_ALLOCATION AfEvent = "FAILED_RESOURCES_ALLOCATION"
        AfEvent_OUT_OF_CREDIT AfEvent = "OUT_OF_CREDIT"
        AfEvent_PDU_SESSION_STATUS AfEvent = "PDU_SESSION_STATUS"
        AfEvent_PLMN_CHG AfEvent = "PLMN_CHG"
        AfEvent_QOS_MONITORING AfEvent = "QOS_MONITORING"
        AfEvent_QOS_NOTIF AfEvent = "QOS_NOTIF"
        AfEvent_RAN_NAS_CAUSE AfEvent = "RAN_NAS_CAUSE"
        AfEvent_REALLOCATION_OF_CREDIT AfEvent = "REALLOCATION_OF_CREDIT"
        AfEvent_SAT_CATEGORY_CHG AfEvent = "SAT_CATEGORY_CHG"
        AfEvent_SUCCESSFUL_QOS_UPDATE AfEvent = "SUCCESSFUL_QOS_UPDATE"
        AfEvent_SUCCESSFUL_RESOURCES_ALLOCATION AfEvent = "SUCCESSFUL_RESOURCES_ALLOCATION"
        AfEvent_TSN_BRIDGE_INFO AfEvent = "TSN_BRIDGE_INFO"
        AfEvent_UP_PATH_CHG_FAILURE AfEvent = "UP_PATH_CHG_FAILURE"
        AfEvent_USAGE_REPORT AfEvent = "USAGE_REPORT"
        AfEvent_UE_TEMPORARILY_UNAVAILABLE AfEvent = "UE_TEMPORARILY_UNAVAILABLE"
        AfEvent_BAT_OFFSET_INFO AfEvent = "BAT_OFFSET_INFO"
        AfEvent_URSP_ENF_INFO AfEvent = "URSP_ENF_INFO"
        AfEvent_PACK_DEL_VAR AfEvent = "PACK_DEL_VAR"
        AfEvent_L4_S_SUPP AfEvent = "L4S_SUPP"
        AfEvent_RT_DELAY_TWO_QOS_FLOWS AfEvent = "RT_DELAY_TWO_QOS_FLOWS"
)



