/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Indicates TSC Traffic QoS.
type TsnQosContainer struct {
	// Unsigned integer indicating Maximum Data Burst Volume (see clauses 5.7.3.7 and 5.7.4 of 3GPP TS 23.501), expressed in Bytes.  
	MaxTscBurstSize int32 `json:"maxTscBurstSize,omitempty" yaml:"maxTscBurstSize" bson:"maxTscBurstSize,omitempty"`
	// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. 
	TscPackDelay int32 `json:"tscPackDelay,omitempty" yaml:"tscPackDelay" bson:"tscPackDelay,omitempty"`
	// String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one decimal digit. 
	MaxPer string `json:"maxPer,omitempty" yaml:"maxPer" bson:"maxPer,omitempty"`
	// Represents the priority level of TSC Flows.
	TscPrioLevel int32 `json:"tscPrioLevel,omitempty" yaml:"tscPrioLevel" bson:"tscPrioLevel,omitempty"`
}


