/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Ellipsoid point with altitude and uncertainty ellipsoid.
type PointAltitudeUncertainty struct {
	Shape SupportedGadShapes `json:"shape,omitempty" yaml:"shape" bson:"shape,omitempty"`
	Point *GeographicalCoordinates `json:"point,omitempty" yaml:"point" bson:"point,omitempty"`
	// Indicates value of altitude.
	Altitude float64 `json:"altitude,omitempty" yaml:"altitude" bson:"altitude,omitempty"`
	UncertaintyEllipse *UncertaintyEllipse `json:"uncertaintyEllipse,omitempty" yaml:"uncertaintyEllipse" bson:"uncertaintyEllipse,omitempty"`
	// Indicates value of uncertainty.
	UncertaintyAltitude float32 `json:"uncertaintyAltitude,omitempty" yaml:"uncertaintyAltitude" bson:"uncertaintyAltitude,omitempty"`
	// Indicates value of confidence.
	Confidence int32 `json:"confidence,omitempty" yaml:"confidence" bson:"confidence,omitempty"`
	// Indicates value of confidence.
	VConfidence int32 `json:"vConfidence,omitempty" yaml:"vConfidence" bson:"vConfidence,omitempty"`
}


