/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the UP path change event subscription from the AF.
type UpPathChgEvent struct {
	// String providing an URI formatted according to RFC 3986.
	NotificationUri string `json:"notificationUri,omitempty" yaml:"notificationUri" bson:"notificationUri,omitempty"`
	// It is used to set the value of Notification Correlation ID in the notification sent by the SMF. 
	NotifCorreId string `json:"notifCorreId,omitempty" yaml:"notifCorreId" bson:"notifCorreId,omitempty"`
	DnaiChgType DnaiChangeType `json:"dnaiChgType,omitempty" yaml:"dnaiChgType" bson:"dnaiChgType,omitempty"`
	AfAckInd bool `json:"afAckInd,omitempty" yaml:"afAckInd" bson:"afAckInd,omitempty"`
}

