/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Represents a QoS monitoring report.
type QosMonitoringReport struct {
	UlDelays []int32 `json:"ulDelays,omitempty" yaml:"ulDelays" bson:"ulDelays,omitempty"`
	DlDelays []int32 `json:"dlDelays,omitempty" yaml:"dlDelays" bson:"dlDelays,omitempty"`
	RtDelays []int32 `json:"rtDelays,omitempty" yaml:"rtDelays" bson:"rtDelays,omitempty"`
	// Represents the packet delay measurement failure indicator.
	Pdmf bool `json:"pdmf,omitempty" yaml:"pdmf" bson:"pdmf,omitempty"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	UlDataRate string `json:"ulDataRate,omitempty" yaml:"ulDataRate" bson:"ulDataRate,omitempty"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	DlDataRate string `json:"dlDataRate,omitempty" yaml:"dlDataRate" bson:"dlDataRate,omitempty"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	UlAggrDataRate string `json:"ulAggrDataRate,omitempty" yaml:"ulAggrDataRate" bson:"ulAggrDataRate,omitempty"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	DlAggrDataRate string `json:"dlAggrDataRate,omitempty" yaml:"dlAggrDataRate" bson:"dlAggrDataRate,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UlConInfo int32 `json:"ulConInfo,omitempty" yaml:"ulConInfo" bson:"ulConInfo,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	DlConInfo int32 `json:"dlConInfo,omitempty" yaml:"dlConInfo" bson:"dlConInfo,omitempty"`
}


