/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the acceptable range (which is formulated as lower bound and upper bound of the periodicity of the start twobursts in reference to the external GM) or acceptable periodicity value(s) (which is formulated as a list of values for the periodicity). 
type PeriodicityRange struct {
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	LowerBound int32 `json:"lowerBound,omitempty" yaml:"lowerBound" bson:"lowerBound,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UpperBound int32 `json:"upperBound,omitempty" yaml:"upperBound" bson:"upperBound,omitempty"`
	PeriodicVals []int32 `json:"periodicVals,omitempty" yaml:"periodicVals" bson:"periodicVals,omitempty"`
}


