/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// A range of Group IDs (internal group identities), either based on a numeric range, or based on regular-expression matching
type InternalGroupIdRange struct {
	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.
	Start string `json:"start,omitempty" yaml:"start" bson:"start" mapstructure:"Start"`
	// String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.
	End     string `json:"end,omitempty" yaml:"end" bson:"end" mapstructure:"End"`
	Pattern string `json:"pattern,omitempty" yaml:"pattern" bson:"pattern" mapstructure:"Pattern"`
}
