/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Parameters supported by an TSCTSF for a given DNN
type DnnTsctsfInfoItem struct {
	Dnn interface{} `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
}
