/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the Time Synchronization Configuration parameters.
type TimeSyncExposureConfig2 struct {
	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	UpNodeId int32 `json:"upNodeId" yaml:"upNodeId" bson:"upNodeId" mapstructure:"UpNodeId"`
	ReqPtpIns *PtpInstance2 `json:"reqPtpIns" yaml:"reqPtpIns" bson:"reqPtpIns" mapstructure:"ReqPtpIns"`
	// Indicates that the AF requests 5GS to act as a grandmaster for PTP or gPTP if it is included and set to true. 
	GmEnable bool `json:"gmEnable,omitempty" yaml:"gmEnable" bson:"gmEnable" mapstructure:"GmEnable"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	GmPrio int32 `json:"gmPrio,omitempty" yaml:"gmPrio" bson:"gmPrio" mapstructure:"GmPrio"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	TimeDom int32 `json:"timeDom" yaml:"timeDom" bson:"timeDom" mapstructure:"TimeDom"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	TimeSyncErrBdgt int32 `json:"timeSyncErrBdgt,omitempty" yaml:"timeSyncErrBdgt" bson:"timeSyncErrBdgt" mapstructure:"TimeSyncErrBdgt"`
	// Notification Correlation ID assigned by the NF service consumer.
	ConfigNotifId string `json:"configNotifId" yaml:"configNotifId" bson:"configNotifId" mapstructure:"ConfigNotifId"`
	// String providing an URI formatted according to RFC 3986.
	ConfigNotifUri string `json:"configNotifUri" yaml:"configNotifUri" bson:"configNotifUri" mapstructure:"ConfigNotifUri"`
	TempValidity *TemporalValidity `json:"tempValidity,omitempty" yaml:"tempValidity" bson:"tempValidity" mapstructure:"TempValidity"`
}
