/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)


type SupportedGadShapes string

// List of SupportedGADShapes
const (
        SupportedGadShapes_POINT SupportedGadShapes = "POINT"
        SupportedGadShapes_POINT_UNCERTAINTY_CIRCLE SupportedGadShapes = "POINT_UNCERTAINTY_CIRCLE"
        SupportedGadShapes_POINT_UNCERTAINTY_ELLIPSE SupportedGadShapes = "POINT_UNCERTAINTY_ELLIPSE"
        SupportedGadShapes_POLYGON SupportedGadShapes = "POLYGON"
        SupportedGadShapes_POINT_ALTITUDE SupportedGadShapes = "POINT_ALTITUDE"
        SupportedGadShapes_POINT_ALTITUDE_UNCERTAINTY SupportedGadShapes = "POINT_ALTITUDE_UNCERTAINTY"
        SupportedGadShapes_ELLIPSOID_ARC SupportedGadShapes = "ELLIPSOID_ARC"
        SupportedGadShapes_LOCAL_2_D_POINT_UNCERTAINTY_ELLIPSE SupportedGadShapes = "LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE"
        SupportedGadShapes_LOCAL_3_D_POINT_UNCERTAINTY_ELLIPSOID SupportedGadShapes = "LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID"
        SupportedGadShapes_DISTANCE_DIRECTION SupportedGadShapes = "DISTANCE_DIRECTION"
        SupportedGadShapes_RELATIVE_2_D_LOCATION_UNCERTAINTY_ELLIPSE SupportedGadShapes = "RELATIVE_2D_LOCATION_UNCERTAINTY_ELLIPSE"
        SupportedGadShapes_RELATIVE_3_D_LOCATION_UNCERTAINTY_ELLIPSOID SupportedGadShapes = "RELATIVE_3D_LOCATION_UNCERTAINTY_ELLIPSOID"
)



