/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the Time Synchronization Configuration parameters.
type TimeSyncExposureConfig struct {
	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	UpNodeId int32 `json:"upNodeId,omitempty" yaml:"upNodeId" bson:"upNodeId,omitempty"`
	ReqPtpIns *PtpInstance `json:"reqPtpIns,omitempty" yaml:"reqPtpIns" bson:"reqPtpIns,omitempty"`
	// Indicates that the AF requests 5GS to act as a grandmaster for PTP or gPTP if it is  included and set to true. 
	GmEnable bool `json:"gmEnable,omitempty" yaml:"gmEnable" bson:"gmEnable,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	GmPrio int32 `json:"gmPrio,omitempty" yaml:"gmPrio" bson:"gmPrio,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	TimeDom int32 `json:"timeDom,omitempty" yaml:"timeDom" bson:"timeDom,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	TimeSyncErrBdgt int32 `json:"timeSyncErrBdgt,omitempty" yaml:"timeSyncErrBdgt" bson:"timeSyncErrBdgt,omitempty"`
	// Notification Correlation ID assigned by the NF service consumer.
	ConfigNotifId string `json:"configNotifId,omitempty" yaml:"configNotifId" bson:"configNotifId,omitempty"`
	// String providing an URI formatted according to RFC 3986.
	ConfigNotifUri string `json:"configNotifUri,omitempty" yaml:"configNotifUri" bson:"configNotifUri,omitempty"`
	TempValidity *TemporalValidity `json:"tempValidity,omitempty" yaml:"tempValidity" bson:"tempValidity,omitempty"`
	// Identifies a list of Tracking Areas per serving network where time synchronization service configuration is allowed. 
	CovReq []ServiceAreaCoverageInfo `json:"covReq,omitempty" yaml:"covReq" bson:"covReq,omitempty"`
	ClkQltDetLvl ClockQualityDetailLevel `json:"clkQltDetLvl,omitempty" yaml:"clkQltDetLvl" bson:"clkQltDetLvl,omitempty"`
	ClkQltAcptCri *ClockQualityAcceptanceCriterion `json:"clkQltAcptCri,omitempty" yaml:"clkQltAcptCri" bson:"clkQltAcptCri,omitempty"`
}


