/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the capability of time synchronization service.
type TimeSyncCapability struct {
	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	UpNodeId int32 `json:"upNodeId,omitempty" yaml:"upNodeId" bson:"upNodeId,omitempty"`
	GmCapables []GmCapable `json:"gmCapables,omitempty" yaml:"gmCapables" bson:"gmCapables,omitempty"`
	AsTimeRes AsTimeResource `json:"asTimeRes,omitempty" yaml:"asTimeRes" bson:"asTimeRes,omitempty"`
	// Contains the PTP capabilities supported by each of the SUPI(s). The key of the map is the SUPI. 
	PtpCapForUes map[string]PtpCapabilitiesPerUe `json:"ptpCapForUes,omitempty" yaml:"ptpCapForUes" bson:"ptpCapForUes,omitempty"`
	// Contains the PTP capabilities supported by each of the GPSI(s). The key of the map is the GPSI. 
	PtpCapForGpsis map[string]PtpCapabilitiesPerUe `json:"ptpCapForGpsis,omitempty" yaml:"ptpCapForGpsis" bson:"ptpCapForGpsis,omitempty"`
}


