/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Represents an Individual TSC Application Session Context resource.
type TscAppSessionContextData struct {
	UeIpAddr *IpAddr `json:"ueIpAddr,omitempty" yaml:"ueIpAddr" bson:"ueIpAddr,omitempty"`
	// The IPv4 address domain identifier.
	IpDomain string `json:"ipDomain,omitempty" yaml:"ipDomain" bson:"ipDomain,omitempty"`
	// String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. 
	UeMac string `json:"ueMac,omitempty" yaml:"ueMac" bson:"ueMac,omitempty"`
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	UeId string `json:"ueId,omitempty" yaml:"ueId" bson:"ueId,omitempty"`
	// String identifying External Group Identifier that identifies a group made up of one or more  subscriptions associated to a group of IMSIs, as specified in clause 19.7.3 of 3GPP TS 23.003.  
	ExternalGroupId string `json:"externalGroupId,omitempty" yaml:"externalGroupId" bson:"externalGroupId,omitempty"`
	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). 
	Dnn string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn,omitempty"`
	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai,omitempty"`
	// String providing an URI formatted according to RFC 3986.
	NotifUri string `json:"notifUri,omitempty" yaml:"notifUri" bson:"notifUri,omitempty"`
	// Identifies the Application Identifier.
	AppId string `json:"appId,omitempty" yaml:"appId" bson:"appId,omitempty"`
	EthFlowInfo []EthFlowDescription `json:"ethFlowInfo,omitempty" yaml:"ethFlowInfo" bson:"ethFlowInfo,omitempty"`
	// Identifies the Ethernet flows which require QoS. Each Ethernet flow consists of a flow identifer and the corresponding UL and/or DL flows. 
	EnEthFlowInfo []EthFlowInfo `json:"enEthFlowInfo,omitempty" yaml:"enEthFlowInfo" bson:"enEthFlowInfo,omitempty"`
	FlowInfo []FlowInfo `json:"flowInfo,omitempty" yaml:"flowInfo" bson:"flowInfo,omitempty"`
	// Identifies the AF identifier.
	AfId string `json:"afId,omitempty" yaml:"afId" bson:"afId,omitempty"`
	TscQosReq *TscQosRequirement `json:"tscQosReq,omitempty" yaml:"tscQosReq" bson:"tscQosReq,omitempty"`
	// Identifies a pre-defined QoS information.
	QosReference string `json:"qosReference,omitempty" yaml:"qosReference" bson:"qosReference,omitempty"`
	// Identifies an ordered list of pre-defined QoS information.
	AltQosReferences []string `json:"altQosReferences,omitempty" yaml:"altQosReferences" bson:"altQosReferences,omitempty"`
	// Identifies an ordered list of alternative service requirements that include individual QoS parameter sets. The lower the index of the array for a given entry, the higher the priority. 
	AltQosReqs []AlternativeServiceRequirementsData `json:"altQosReqs,omitempty" yaml:"altQosReqs" bson:"altQosReqs,omitempty"`
	// Contains an identity of an application service provider.
	AspId string `json:"aspId,omitempty" yaml:"aspId" bson:"aspId,omitempty"`
	// Contains an identity of a sponsor.
	SponId string `json:"sponId,omitempty" yaml:"sponId" bson:"sponId,omitempty"`
	SponStatus SponsoringStatus `json:"sponStatus,omitempty" yaml:"sponStatus" bson:"sponStatus,omitempty"`
	EvSubsc *EventsSubscReqData `json:"evSubsc,omitempty" yaml:"evSubsc" bson:"evSubsc,omitempty"`
	TempInValidity *TemporalInValidity `json:"tempInValidity,omitempty" yaml:"tempInValidity" bson:"tempInValidity,omitempty"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SuppFeat string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat,omitempty"`
}

