/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains Clock Quality.
type ClockQuality struct {
	TraceabilityToGnss bool `json:"traceabilityToGnss,omitempty" yaml:"traceabilityToGnss" bson:"traceabilityToGnss,omitempty"`
	TraceabilityToUtc bool `json:"traceabilityToUtc,omitempty" yaml:"traceabilityToUtc" bson:"traceabilityToUtc,omitempty"`
	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer. 
	FrequencyStability int32 `json:"frequencyStability,omitempty" yaml:"frequencyStability" bson:"frequencyStability,omitempty"`
	ClockAccuracyIndex string `json:"clockAccuracyIndex,omitempty" yaml:"clockAccuracyIndex" bson:"clockAccuracyIndex,omitempty"`
	ClockAccuracyValue int32 `json:"clockAccuracyValue,omitempty" yaml:"clockAccuracyValue" bson:"clockAccuracyValue,omitempty"`
}

