/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the UMIC.
type BridgeManagementContainer struct {
	// string with format 'bytes' as defined in OpenAPI
	BridgeManCont []uint8 `json:"bridgeManCont" yaml:"bridgeManCont" bson:"bridgeManCont" mapstructure:"BridgeManCont"`
}
