/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Set of parameters supported by TSCTSF for a given S-NSSAI
type SnssaiTsctsfInfoItem struct {
	SNssai      *ExtSnssai          `json:"sNssai" yaml:"sNssai" bson:"sNssai" mapstructure:"SNssai"`
	DnnInfoList []DnnTsctsfInfoItem `json:"dnnInfoList" yaml:"dnnInfoList" bson:"dnnInfoList" mapstructure:"DnnInfoList"`
}
