/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Ellipsoid Arc.
type EllipsoidArc struct {
	Shape SupportedGadShapes `json:"shape,omitempty" yaml:"shape" bson:"shape,omitempty"`
	Point *GeographicalCoordinates `json:"point,omitempty" yaml:"point" bson:"point,omitempty"`
	// Indicates value of the inner radius.
	InnerRadius int32 `json:"innerRadius,omitempty" yaml:"innerRadius" bson:"innerRadius,omitempty"`
	// Indicates value of uncertainty.
	UncertaintyRadius float32 `json:"uncertaintyRadius,omitempty" yaml:"uncertaintyRadius" bson:"uncertaintyRadius,omitempty"`
	// Indicates value of angle.
	OffsetAngle int32 `json:"offsetAngle,omitempty" yaml:"offsetAngle" bson:"offsetAngle,omitempty"`
	// Indicates value of angle.
	IncludedAngle int32 `json:"includedAngle,omitempty" yaml:"includedAngle" bson:"includedAngle,omitempty"`
	// Indicates value of confidence.
	Confidence int32 `json:"confidence,omitempty" yaml:"confidence" bson:"confidence,omitempty"`
}

