/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the port management information container for a port.
type PortManagementContainer struct {
	// string with format 'bytes' as defined in OpenAPI
	PortManCont []uint8 `json:"portManCont" yaml:"portManCont" bson:"portManCont" mapstructure:"PortManCont"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	PortNum uint32 `json:"portNum" yaml:"portNum" bson:"portNum" mapstructure:"PortNum"`
}
