/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Indicates the offset of the BAT and the optionally adjusted periodicity. 
type BatOffsetInfo struct {
	// Indicates the BAT offset of the arrival time of the data burst in units of milliseconds. 
	RanBatOffsetNotif int32 `json:"ranBatOffsetNotif,omitempty" yaml:"ranBatOffsetNotif" bson:"ranBatOffsetNotif,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AdjPeriod int32 `json:"adjPeriod,omitempty" yaml:"adjPeriod" bson:"adjPeriod,omitempty"`
	// Identification of the flows. If no flows are provided, the BAT offset applies for all flows of the AF session. 
	Flows []Flows `json:"flows,omitempty" yaml:"flows" bson:"flows,omitempty"`
}


