/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Describes a notification of an matched event.
type EventNotification struct {
	Event TscEvent `json:"event,omitempty" yaml:"event" bson:"event,omitempty"`
	// Identifies the IP flows that were sent during event subscription.
	FlowIds []int32 `json:"flowIds,omitempty" yaml:"flowIds" bson:"flowIds,omitempty"`
	QosMonReports []QosMonitoringReport `json:"qosMonReports,omitempty" yaml:"qosMonReports" bson:"qosMonReports,omitempty"`
	UsgRep *AccumulatedUsage `json:"usgRep,omitempty" yaml:"usgRep" bson:"usgRep,omitempty"`
	// The currently applied alternative QoS requirement referring to an alternative QoS reference or a requested alternative QoS parameter set. Applicable for event QOS_NOT_GUARANTEED or SUCCESSFUL_RESOURCES_ALLOCATION. 
	AppliedQosRef string `json:"appliedQosRef,omitempty" yaml:"appliedQosRef" bson:"appliedQosRef,omitempty"`
	// When present and set to true it indicates that the Alternative QoS profiles are not  supported by NG-RAN. Applicable for event QOS_NOT_GUARANTEED or SUCCESSFUL_RESOURCES_ALLOCATION. 
	AltQosNotSuppInd bool `json:"altQosNotSuppInd,omitempty" yaml:"altQosNotSuppInd" bson:"altQosNotSuppInd,omitempty"`
}


