/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
    "time"
)



// Indicates TSC Traffic pattern.
type TscaiInputContainer struct {
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Periodicity int32 `json:"periodicity,omitempty" yaml:"periodicity" bson:"periodicity,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	BurstArrivalTime *time.Time `json:"burstArrivalTime,omitempty" yaml:"burstArrivalTime" bson:"burstArrivalTime,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	SurTimeInNumMsg int32 `json:"surTimeInNumMsg,omitempty" yaml:"surTimeInNumMsg" bson:"surTimeInNumMsg,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	SurTimeInTime int32 `json:"surTimeInTime,omitempty" yaml:"surTimeInTime" bson:"surTimeInTime,omitempty"`
	BurstArrivalTimeWnd *TimeWindow `json:"burstArrivalTimeWnd,omitempty" yaml:"burstArrivalTimeWnd" bson:"burstArrivalTimeWnd,omitempty"`
	PeriodicityRange *PeriodicityRange `json:"periodicityRange,omitempty" yaml:"periodicityRange" bson:"periodicityRange,omitempty"`
}


