/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the notification of time synchronization service state.
type TimeSyncExposureConfigNotif struct {
	// Notification Correlation ID assigned by the NF service consumer.
	ConfigNotifId string `json:"configNotifId,omitempty" yaml:"configNotifId" bson:"configNotifId,omitempty"`
	StateOfConfig *StateOfConfiguration `json:"stateOfConfig,omitempty" yaml:"stateOfConfig" bson:"stateOfConfig,omitempty"`
}

