/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Describes the authorization data of an Individual TSC Application Session Context created by the PCF. 
type TscAppSessionContextUpdateData struct {
	// String providing an URI formatted according to RFC 3986.
	NotifUri string `json:"notifUri,omitempty" yaml:"notifUri" bson:"notifUri,omitempty"`
	// Identifies the Application Identifier.
	AppId string `json:"appId,omitempty" yaml:"appId" bson:"appId,omitempty"`
	EthFlowInfo []EthFlowDescription `json:"ethFlowInfo,omitempty" yaml:"ethFlowInfo" bson:"ethFlowInfo,omitempty"`
	// Identifies the Ethernet flows which require QoS. Each Ethernet flow consists of a flow identifer and the corresponding UL and/or DL flows. 
	EnEthFlowInfo []EthFlowInfo `json:"enEthFlowInfo,omitempty" yaml:"enEthFlowInfo" bson:"enEthFlowInfo,omitempty"`
	FlowInfo []FlowInfo `json:"flowInfo,omitempty" yaml:"flowInfo" bson:"flowInfo,omitempty"`
	TscQosReq *TscQosRequirementRm `json:"tscQosReq,omitempty" yaml:"tscQosReq" bson:"tscQosReq,omitempty"`
	// Identifies a pre-defined QoS information.
	QosReference string `json:"qosReference,omitempty" yaml:"qosReference" bson:"qosReference,omitempty"`
	// Identifies an ordered list of pre-defined QoS information.
	AltQosReferences []string `json:"altQosReferences,omitempty" yaml:"altQosReferences" bson:"altQosReferences,omitempty"`
	// Identifies an ordered list of alternative service requirements that include individual QoS parameter sets. The lower the index of the array for a given entry, the higher the priority. 
	AltQosReqs []AlternativeServiceRequirementsData `json:"altQosReqs,omitempty" yaml:"altQosReqs" bson:"altQosReqs,omitempty"`
	// Contains an identity of an application service provider.
	AspId string `json:"aspId,omitempty" yaml:"aspId" bson:"aspId,omitempty"`
	// Contains an identity of a sponsor.
	SponId string `json:"sponId,omitempty" yaml:"sponId" bson:"sponId,omitempty"`
	SponStatus SponsoringStatus `json:"sponStatus,omitempty" yaml:"sponStatus" bson:"sponStatus,omitempty"`
	EvSubsc *EventsSubscReqDataRm `json:"evSubsc,omitempty" yaml:"evSubsc" bson:"evSubsc,omitempty"`
	TempInValidity *TemporalInValidity `json:"tempInValidity,omitempty" yaml:"tempInValidity" bson:"tempInValidity,omitempty"`
}

