/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Identifies the flows.
type Flows struct {
	ContVers []int32 `json:"contVers,omitempty" yaml:"contVers" bson:"contVers,omitempty"`
	FNums []int32 `json:"fNums,omitempty" yaml:"fNums" bson:"fNums,omitempty"`
	MedCompN int32 `json:"medCompN,omitempty" yaml:"medCompN" bson:"medCompN,omitempty"`
}

