/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)


type InstanceType string

// List of InstanceType
const (
        InstanceType_BOUNDARY_CLOCK InstanceType = "BOUNDARY_CLOCK"
        InstanceType_E2_E_TRANS_CLOCK InstanceType = "E2E_TRANS_CLOCK"
        InstanceType_P2_P_TRANS_CLOCK InstanceType = "P2P_TRANS_CLOCK"
        InstanceType_P2_P_RELAY_INSTANCE InstanceType = "P2P_RELAY_INSTANCE"
)




