/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)


type TimeSource string

// List of TimeSource
const (
        TimeSource_SYNC_E TimeSource = "SYNC_E"
        TimeSource_PTP TimeSource = "PTP"
        TimeSource_GNSS TimeSource = "GNSS"
        TimeSource_ATOMIC_CLOCK TimeSource = "ATOMIC_CLOCK"
        TimeSource_TERRESTRIAL_RADIO TimeSource = "TERRESTRIAL_RADIO"
        TimeSource_SERIAL_TIME_CODE TimeSource = "SERIAL_TIME_CODE"
        TimeSource_NTP TimeSource = "NTP"
        TimeSource_HAND_SET TimeSource = "HAND_SET"
        TimeSource_OTHER TimeSource = "OTHER"
)



