/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Represents the PDU Set level QoS parameters.
type PduSetQosPara struct {
	// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501 [8])), expressed in 0.01 milliseconds. 
	PduSetDelayBudget int32 `json:"pduSetDelayBudget,omitempty" yaml:"pduSetDelayBudget" bson:"pduSetDelayBudget,omitempty"`
	// String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \"scalar x 10-k\" where the scalar and the exponent k are each encoded as one decimal digit. 
	PduSetErrRate string `json:"pduSetErrRate,omitempty" yaml:"pduSetErrRate" bson:"pduSetErrRate,omitempty"`
	PduSetHandlingInfo PduSetHandlingInfo `json:"pduSetHandlingInfo,omitempty" yaml:"pduSetHandlingInfo" bson:"pduSetHandlingInfo,omitempty"`
}

