/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the information for traffic correlation. 
type TrafficCorrelationInfo struct {
	CorrType CorrelationType `json:"corrType,omitempty" yaml:"corrType" bson:"corrType,omitempty"`
	// Identification of a set of UEs accessing the application identified by the  Application Identifier or traffic filtering information. 
	TfcCorrId string `json:"tfcCorrId,omitempty" yaml:"tfcCorrId" bson:"tfcCorrId,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166 with the OpenAPI defined 'nullable: true' property. 
	ComEasIpv4Addr string `json:"comEasIpv4Addr,omitempty" yaml:"comEasIpv4Addr" bson:"comEasIpv4Addr,omitempty"`
	ComEasIpv6Addr string `json:"comEasIpv6Addr,omitempty" yaml:"comEasIpv6Addr" bson:"comEasIpv6Addr,omitempty"`
	FqdnRange []FqdnPatternMatchingRule `json:"fqdnRange,omitempty" yaml:"fqdnRange" bson:"fqdnRange,omitempty"`
	// String providing an URI formatted according to RFC 3986 with the OpenAPI 'nullable: true' property. 
	NotifUri string `json:"notifUri,omitempty" yaml:"notifUri" bson:"notifUri,omitempty"`
	// Notification correlation identifier.
	NotifCorrId string `json:"notifCorrId,omitempty" yaml:"notifCorrId" bson:"notifCorrId,omitempty"`
}

