/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// The response shall include a Location header field containing a different URI  (pointing to a different URI of an other service instance), or the same URI if a request  is redirected to the same target resource via a different SCP. 
type RedirectResponse struct {
	Cause string `json:"cause,omitempty" yaml:"cause" bson:"cause,omitempty"`
	// String providing an URI formatted according to RFC 3986.
	TargetScp string `json:"targetScp,omitempty" yaml:"targetScp" bson:"targetScp,omitempty"`
	// String providing an URI formatted according to RFC 3986.
	TargetSepp string `json:"targetSepp,omitempty" yaml:"targetSepp" bson:"targetSepp,omitempty"`
}


