/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
    "time"
)



// Indicates the time interval(s) during which the AF request is to be applied.
type TemporalValidity struct {
	// string with format 'date-time' as defined in OpenAPI.
	StartTime *time.Time `json:"startTime,omitempty" yaml:"startTime" bson:"startTime,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	StopTime *time.Time `json:"stopTime,omitempty" yaml:"stopTime" bson:"stopTime,omitempty"`
}

