/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Represents the IP address and port of an EAS server.
type EasServerAddress struct {
	Ip *IpAddr `json:"ip,omitempty" yaml:"ip" bson:"ip,omitempty"`
	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Port int32 `json:"port,omitempty" yaml:"port" bson:"port,omitempty"`
}

