/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)


type TerminationCause string

// List of TerminationCause
const (
        TerminationCause_ALL_SDF_DEACTIVATION TerminationCause = "ALL_SDF_DEACTIVATION"
        TerminationCause_PDU_SESSION_TERMINATION TerminationCause = "PDU_SESSION_TERMINATION"
        TerminationCause_PS_TO_CS_HO TerminationCause = "PS_TO_CS_HO"
        TerminationCause_INSUFFICIENT_SERVER_RESOURCES TerminationCause = "INSUFFICIENT_SERVER_RESOURCES"
        TerminationCause_INSUFFICIENT_QOS_FLOW_RESOURCES TerminationCause = "INSUFFICIENT_QOS_FLOW_RESOURCES"
        TerminationCause_SPONSORED_DATA_CONNECTIVITY_DISALLOWED TerminationCause = "SPONSORED_DATA_CONNECTIVITY_DISALLOWED"
)




