/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Local 2D point with uncertainty ellipse
type Local2dPointUncertaintyEllipse struct {
	Shape SupportedGadShapes `json:"shape,omitempty" yaml:"shape" bson:"shape,omitempty"`
	LocalOrigin *LocalOrigin `json:"localOrigin,omitempty" yaml:"localOrigin" bson:"localOrigin,omitempty"`
	Point *RelativeCartesianLocation `json:"point,omitempty" yaml:"point" bson:"point,omitempty"`
	UncertaintyEllipse *UncertaintyEllipse `json:"uncertaintyEllipse,omitempty" yaml:"uncertaintyEllipse" bson:"uncertaintyEllipse,omitempty"`
	// Indicates value of confidence.
	Confidence int32 `json:"confidence,omitempty" yaml:"confidence" bson:"confidence,omitempty"`
}

