/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.5.0; 5G System; Time Sensitive Communication and Time Synchronization Function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Contains the state of the time synchronization configuration and the clock quality acceptance criteria result. 
type StateOfConfiguration struct {
	// When any of the PTP port state(s)in NW-TT is Leader, Follower or Passive, it is included and set to trueto indicate the current state of the time synchronization configuration for the NW-TT port(s) of the PTP instance is active; when PTP port state isin any other case, it is included and set to false to indicate the state ofconfiguration for the NW-TT port(s) of the PTP instance is inactive. Default value is false. 
	StateNwtt bool `json:"stateNwtt,omitempty" yaml:"stateNwtt" bson:"stateNwtt,omitempty"`
	ClkQltIndOfNwtt AcceptanceCriteriaResultIndication `json:"clkQltIndOfNwtt,omitempty" yaml:"clkQltIndOfNwtt" bson:"clkQltIndOfNwtt,omitempty"`
	// Contains the PTP port states and the clock quality acceptance criteria result of the DS-TT(s). 
	StateOfDstts []StateOfDstt `json:"stateOfDstts,omitempty" yaml:"stateOfDstts" bson:"stateOfDstts,omitempty"`
}

