/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type TscEvent string

// List of TscEvent
const (
	TscEvent_FAILED_RESOURCES_ALLOCATION     TscEvent = "FAILED_RESOURCES_ALLOCATION"
	TscEvent_QOS_MONITORING                  TscEvent = "QOS_MONITORING"
	TscEvent_QOS_GUARANTEED                  TscEvent = "QOS_GUARANTEED"
	TscEvent_QOS_NOT_GUARANTEED              TscEvent = "QOS_NOT_GUARANTEED"
	TscEvent_SUCCESSFUL_RESOURCES_ALLOCATION TscEvent = "SUCCESSFUL_RESOURCES_ALLOCATION"
	TscEvent_USAGE_REPORT                    TscEvent = "USAGE_REPORT"
	TscEvent_BAT_OFFSET_INFO                 TscEvent = "BAT_OFFSET_INFO"
)
