/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.565 V18.3.0; 5G System; Time Sensitive Communication and Time Synchronization function  Services; Stage 3. 
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.565/
 *
 * API version: 1.1.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	
)



// Describes AF requirements on steering traffic to N6-LAN.
type AfSfcRequirement struct {
	// Reference to a pre-configured SFC for downlink traffic.
	SfcIdDl string `json:"sfcIdDl,omitempty" yaml:"sfcIdDl" bson:"sfcIdDl,omitempty"`
	// Reference to a pre-configured SFC for uplink traffic.
	SfcIdUl string `json:"sfcIdUl,omitempty" yaml:"sfcIdUl" bson:"sfcIdUl,omitempty"`
	SpVal *SpatialValidityRm `json:"spVal,omitempty" yaml:"spVal" bson:"spVal,omitempty"`
	// A String which is transparently passed to the UPF to be applied for traffic to SFC. 
	Metadata string `json:"metadata,omitempty" yaml:"metadata" bson:"metadata,omitempty"`
}

